version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:7.5.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  mdb:
    hostname: mdb
    container_name: mdb
    image: mongo:latest
    restart: always
    expose:
      - 27017
    networks:
      - mdbn
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
      - ./scripts:/scripts
    entrypoint:
      [
        'mongod',
        '--bind_ip_all',
        '--replSet',
        'rs0',
        '--storageEngine=wiredTiger',
      ]

volumes:
  es-data:
  db-data:

networks:
  mdbn:
